# Generated by Django 4.0.4 on 2022-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_speisekarte_anzahl_bestellt'),
    ]

    operations = [
        migrations.AddField(
            model_name='speisekarte',
            name='id_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
