# Generated by Django 4.0.5 on 2022-07-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_alter_speisekarte_preis'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellposition',
            name='preis',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
