# Generated by Django 4.0.4 on 2022-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speisekarte',
            name='anzahl_bestellt',
            field=models.IntegerField(blank=True),
        ),
    ]
