# Generated by Django 4.0.4 on 2023-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_speisekarte_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speisekarte',
            name='anzahl_bestellt',
            field=models.IntegerField(default=0),
        ),
    ]
