# Generated by Django 4.0.5 on 2022-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_speisekarte_kategorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speisekarte',
            name='preis',
            field=models.FloatField(),
        ),
    ]
